"""
Bilingual (English / Hindi) message service for SIH26101.

Serves user-facing dynamic strings: greetings, notices, readiness labels,
next-action titles, and competency plain-titles. Language is selected via
the ?lang=hi query parameter on the routers that use it.
"""

from typing import Optional

VALID_LANGS = ("en", "hi")


def normalize_lang(lang: Optional[str]) -> str:
    """Accepts raw query value, returns 'en' or 'hi'."""
    return "hi" if (lang or "").strip().lower().startswith("hi") else "en"


# ----------------------------------------------------------------------------
# Dashboard greeting + readiness
# ----------------------------------------------------------------------------
GREETINGS = {
    "en": "Welcome back, {name}",
    "hi": "पुनः स्वागत है, {name}",
}

READINESS_LABELS = {
    "READY": {"en": "Learning Readiness: Ready for Advanced Practice",
              "hi": "शिक्षण तत्परता: उन्नत अभ्यास हेतु तैयार"},
    "NEAR_READY": {"en": "Learning Readiness: Near Ready (Minor Gap Remaining)",
                   "hi": "शिक्षण तत्परता: लगभग तैयार (एक छोटा अंतर शेष)"},
    "DEVELOPMENT_REQUIRED": {"en": "Learning Readiness: Guided Development Required",
                             "hi": "शिक्षण तत्परता: निर्देशित विकास आवश्यक"},
    "CRITICAL_GAPS": {"en": "Learning Readiness: Priority Foundational Gaps",
                      "hi": "शिक्षण तत्परता: प्राथमिक आधारभूत अंतर"},
    "INSUFFICIENT_EVIDENCE": {"en": "Learning Readiness: Diagnostic Assessment Required",
                              "hi": "शिक्षण तत्परता: नैदानिक मूल्यांकन आवश्यक"},
    "UNKNOWN": {"en": "Under Evaluation", "hi": "मूल्यांकनाधीन"},
}

# ----------------------------------------------------------------------------
# Notices shown under quizzes / assessments / review
# ----------------------------------------------------------------------------
NOTICES = {
    "practice_quiz_ai": {
        "en": ("This practice quiz was freshly generated by the AI Learning Copilot from this lesson's approved transcript. "
               "Practice reinforces your understanding with instant feedback. Practice results never alter your official competency level."),
        "hi": ("यह अभ्यास क्विज़ AI लर्निंग कोपायलट द्वारा इस पाठ की अनुमोदित ट्रांसक्रिप्ट से अभी तैयार की गई है। "
               "अभ्यास तुरंत प्रतिक्रिया के साथ आपकी समझ को सुदृढ़ करता है। अभ्यास परिणाम आपके आधिकारिक दक्षता स्तर को कभी नहीं बदलते।"),
    },
    "practice_quiz": {
        "en": "Practice reinforces your understanding with instant feedback. Practice results never alter your official competency level.",
        "hi": "अभ्यास तुरंत प्रतिक्रिया के साथ आपकी समझ को सुदृढ़ करता है। अभ्यास परिणाम आपके आधिकारिक दक्षता स्तर को कभी नहीं बदलते।",
    },
    "practice_submit": {
        "en": "This practice result helps personalize your learning. It does NOT change your official proficiency level.",
        "hi": "यह अभ्यास परिणाम आपकी शिक्षण को व्यक्तिगत बनाने में सहायक है। यह आपका आधिकारिक दक्षता स्तर नहीं बदलता।",
    },
    "assessment_submit": {
        "en": "Your assessment has been submitted successfully. A supervisor must verify the evidence against the rubric before your proficiency level changes.",
        "hi": "आपका मूल्यांकन सफलतापूर्वक जमा हो गया है। आपका दक्षता स्तर बदलने से पहले पर्यवेक्षक को रूब्रिक के विरुद्ध साक्ष्य का सत्यापन करना होगा।",
    },
    "assessment_pending": {
        "en": "Your previous submission is currently under review by your supervisor.",
        "hi": "आपका पिछला जमा इस समय आपके पर्यवेक्षक द्वारा समीक्षाधीन है।",
    },
    "review_approved": {
        "en": "Assessment verified against rubric {rubric}. Competency '{comp}' updated from Level {before} to Level {after}. Target learning path successfully recalculated.",
        "hi": "मूल्यांकन रूब्रिक {rubric} के विरुद्ध सत्यापित। दक्षता '{comp}' स्तर {before} से स्तर {after} तक अद्यतनित। लक्ष्य शिक्षण पथ सफलतापूर्वक पुनर्गणित।",
    },
    "review_rejected": {
        "en": "Submission marked as Needs Improvement. Learner notified to complete further practice.",
        "hi": "जमा को 'सुधार आवश्यक' चिह्नित किया गया। शिक्षार्थी को अतिरिक्त अभ्यास हेतु सूचित किया गया।",
    },
    "readiness": {
        "en": "Readiness reflects demonstrated competency evidence in official modules. Administrative promotion eligibility is determined separately under MoSPI Cadre Recruitment Rules.",
        "hi": "तत्परता आधिकारिक मॉड्यूल में प्रदर्शित दक्षता साक्ष्य को दर्शाती है। प्रशासनिक पदोन्नति पात्रता MoSPI कैडर भर्ती नियमों के अंतर्गत अलग से निर्धारित होती है।",
    },
}

# ----------------------------------------------------------------------------
# Learner dashboard next-action titles
# ----------------------------------------------------------------------------
NEXT_ACTION_TITLES = {
    "RECOMMENDED_LEARN": {
        "en": "Strengthen Core Competencies",
        "hi": "मूल दक्षताएँ सुदृढ़ करें",
    },
    "RECOMMENDED_SUBTITLE": {
        "en": "Review your recommended learning modules",
        "hi": "आपके अनुशंसित शिक्षण मॉड्यूल देखें",
    },
    "TAKE_PRACTICE": {
        "en": "Practice with Formative Quiz",
        "hi": "प्रारूपणात्मक क्विज़ के साथ अभ्यास करें",
    },
    "START_ASSESSMENT": {
        "en": "Complete Formal Assessment",
        "hi": "औपचारिक मूल्यांकन पूर्ण करें",
    },
    "WAIT_REVIEW": {
        "en": "Awaiting Supervisor Review",
        "hi": "पर्यवेक्षक समीक्षा प्रतीक्षारत",
    },
}

# ----------------------------------------------------------------------------
# Gap status plain labels
# ----------------------------------------------------------------------------
GAP_STATUS_LABELS = {
    "HIGH": {"en": "High Priority Gap", "hi": "उच्च प्राथमिकता अंतर"},
    "MEDIUM": {"en": "Medium Gap", "hi": "मध्यम अंतर"},
    "NO_GAP": {"en": "Requirement Met", "hi": "आवश्यकता पूर्ण"},
    "INSUFFICIENT_EVIDENCE": {"en": "Diagnostic Required", "hi": "नैदानिक आवश्यक"},
}


def notice(key: str, lang: Optional[str] = "en", **kwargs) -> str:
    text = NOTICES.get(key, {}).get(normalize_lang(lang), NOTICES.get(key, {}).get("en", ""))
    return text.format(**kwargs) if kwargs else text


def greeting(name: str, lang: Optional[str] = "en") -> str:
    return GREETINGS[normalize_lang(lang)].format(name=name)


def readiness_label(status: str, lang: Optional[str] = "en") -> str:
    entry = READINESS_LABELS.get(status, READINESS_LABELS["UNKNOWN"])
    return entry[normalize_lang(lang)]


def gap_status_label(status: str, lang: Optional[str] = "en") -> str:
    entry = GAP_STATUS_LABELS.get(status)
    if not entry:
        return status
    return entry[normalize_lang(lang)]
